### ISSUE TITLE
ekg throws segfault while starting

### ISSUE THREAD

**Issue by marcin-github** [porridge/ekg#2]
Hi!
Thank you for great soft!
Unfortunatelly since a couple of days I got problem with ekg, here is backtrace:
```
Reading symbols from /usr/bin/ekg...Reading symbols from /usr/lib64/debug//usr/bin/ekg.debug...done.
done.
[New LWP 20902]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
btCore was generated by `ekg -i -u XXXXXXX'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056233aa913f0 in memset (__len=128, __ch=0, __dest=0x0) at /usr/include/bits/string3.h:90
90        return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
(gdb) bt
#0  0x000056233aa913f0 in memset (__len=128, __ch=0, __dest=0x0) at /usr/include/bits/string3.h:90
#1  handle_common (uin=YYYYYYY, status=1, idescr=0x0, dtime=<optimized out>, ip=0, port=<optimized out>, version=0, image_size=0) at events.c:886
#2  0x000056233aa9220d in handle_notify60 (e=0x56233b2c3920) at events.c:1203
#3  0x000056233aa92995 in handle_event (s=<optimized out>) at events.c:1407
#4  0x000056233aaa2249 in ekg_wait_for_key () at ekg.c:824
#5  0x000056233aab5095 in ui_ncurses_loop () at ui-ncurses.c:4748
#6  0x000056233aa773a9 in main (argc=<optimized out>, argv=<optimized out>) at ekg.c:1678
```
ekg is at latest commit, ncurses 6.0.

**Comment by porridge** [comment]
This repository is obsolete. The only thing I can suggest is that you take a look at the code at http://ekg.chmurka.net/download.php - it seems to have a few changes on top of the one in this repo.
